<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\css\**" />
    <Content Remove="wwwroot\css\**" />
    <EmbeddedResource Remove="wwwroot\css\**" />
    <None Remove="wwwroot\css\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\Pages\Todo.razor.css" />
  </ItemGroup>

</Project>
